### ISSUE TITLE
SPL token mint 

### ISSUE THREAD

**Issue by PapaBambinoman** [wearekite/candy-machine-v3-ui#12]
i cant figure out how to make my mint with a SPL token, used the versel app and still not working. how does this UI pull the guards?

**Comment by wearekite** [comment]
Hey, the UI pulls the guards directly from your Candy Machine.

**Comment by PapaBambinoman** [comment]
yes when using versel app it shows but wont connect to CM, but when building it thru terminal does not seem to be working , .env file wont load the extra setting,  for the token. what could i be doing wrong

**Comment by wearekite** [comment]
The .env file is being overwritten in the `config.ts`, you can manually override it.

**Comment by wearekite** [comment]
Closed due to inactivity
