### ISSUE TITLE
How to use the UI for mint pNFT 

### ISSUE THREAD

**Issue by MySerpents** [wearekite/candy-machine-v3-ui#13]
Hello, i have tried to use the UI for pNFT mint but I figure out is not compatible rn. I have made a seld code UI but i meet some problems with UI related to label guards for dividing the mint on different phases. Do you have something on the draft that can be used or any clue about that? I am available to check also for testing. Let me know eventually how to add you on discord if available.

**Comment by wearekite** [comment]
pNFTs are as of writing this not yet supported by this UI.

I am planning on implementing this in the future, but currently am too busy with paid work
