### ISSUE TITLE
How can using with whitelist based example minting for OG, WL and Public ?

### ISSUE THREAD

**Issue by cantiir2** [wearekite/candy-machine-v3-ui#3]

**Comment by wearekite** [comment]
Hey @cantiir2,

Do you mean how to use the UI with multiple guard groups?

**Comment by cantiir2** [comment]
Yeah fam, how can add address for allow mint here ?

**Comment by averil7** [comment]
yeah I need that too

**Comment by wearekite** [comment]
I haven't pushed the mint group branch yet, will work on it

**Comment by wearekite** [comment]
Added this functionality in the [multi-group](https://github.com/wearekite/candy-machine-v3-ui/tree/multi-group) branche.

If you come across any other issues be sure to let us know.
