### ISSUE TITLE
Multigroup no exported member 'CandyMachineV3'

### ISSUE THREAD

**Issue by johnt1314** [wearekite/candy-machine-v3-ui#4]
Multigroup occurred error.
`Module '"../hooks/types"' has no exported member 'CandyMachineV3'.`

<img width="555" alt="Screenshot 2023-03-16 at 12 51 48 PM" src="https://user-images.githubusercontent.com/25381530/225517744-8fe33ed7-9a62-4eed-bd64-db5e3008f8e2.png">

**Comment by wearekite** [comment]
Shouldn't be a problem for launching your CM

**Comment by EagTf** [comment]
hey! i have similar problem, any idea why would that happen?

**Comment by wearekite** [comment]
Fixed in the latest update, export was setup wrong
